### ISSUE TITLE
Accurate Acre Images

### ISSUE THREAD

**Issue by Cuyler36** [Cuyler36/ACSE-OLD#1]
The Island Acres need Acre Editor images. There are default ones for Island Left & Right (2), but they aren't size accurate.

**Comment by kitschypop** [comment]
I can help out with graphics

**Comment by Cuyler36** [comment]
I'd very much appreciate the help! If you want to create only accurate island images, then that's fine. If you feel like making acre images (for all acres) like how NLSE has them, then you are welcome to as well. It's not a necessity, but I was considering doing it after the core features are complete.

**Comment by kitschypop** [comment]
Message me on skype?

**Comment by Cuyler36** [comment]
Sure, my Skype is cuyler.36

**Comment by Cuyler36** [comment]
Done.

**Comment by Cuyler36** [comment]
Opened again until all acres have a "real" image.

**Comment by bokkobo** [comment]
I'd like if the acre maps included the large bushes and also ponds, if that wasn't already planned

I could try and help with graphics if it's still needed?

**Comment by Cuyler36** [comment]
That was planned. I've been taking screenshots from a modified version of Dolphin I made for the assets. It sets the camera top-down so I can get a view of the map properly. There are a ton of acres, however, and I've been busy with making the unified editor. Anyways, here's what it will look like for the GameCube games:

![037c](https://cloud.githubusercontent.com/assets/24523422/25074196/b6afee86-22c3-11e7-992e-72458f70dedf.jpg)

![0084](https://cloud.githubusercontent.com/assets/24523422/25074197/bcf00cc2-22c3-11e7-8e6b-b779f1c98928.jpg)

**Comment by bokkobo** [comment]
oh, nice!! this is great work you're doing : ) can't wait to see it!

**Comment by Cuyler36** [comment]
Already finished in the new ACSE: https://github.com/Cuyler36/ACSE
