### ISSUE TITLE
Dōbutsu no Mori +/e+ Support

### ISSUE THREAD

**Issue by kitschypop** [Cuyler36/ACSE-OLD#2]
Dual e+ support for japanese version

**Comment by Cuyler36** [comment]
I plan to eventually add support for (both?) versions of the Japanese games. I'm not sure how many things they changed, and I know only basic Japanese. Hopefully after I finish all the core features, this will happen.

**Comment by Cuyler36** [comment]
Already in the new ACSE: https://github.com/Cuyler36/ACSE
