### ISSUE TITLE
[Feature Request] Change NPC clothing

### ISSUE THREAD

**Issue by Rupert484** [Cuyler36/ACSE-OLD#6]
It would be useful to be able to change the shirt/pattern that a villager/supported NPC is currently wearing.
If this is already a feature, I have hopelessly missed it and apologize.

**Comment by Cuyler36** [comment]
This is an implemented feature in the next release. Here's a screenshot of what it currently looks like: https://puu.sh/v8lA3/db0c239e6f.png

**Comment by Cuyler36** [comment]
Latest version is here: https://github.com/Cuyler36/ACSE
