### ISSUE TITLE
Villager Personalities

### ISSUE THREAD

**Issue by fredisher** [Cuyler36/ACSE-OLD#7]
Weird error whenever i change a villager's personality. I save and reopen the file and it is back to being "lazy" or other previous personality.

Not sure what is wrong.

**Comment by fredisher** [comment]
Also I am having a hard time figuring our how to set their location in the villager editor. I am not sure how to find the numbers i need to enter into the boxes... Clarification on this would be much appreciated.

**Comment by Cuyler36** [comment]
Version 0.4.4 should have fixed that. Tell me if it's happening with this version:
https://github.com/Cuyler36/ACSE/releases/tag/0.4.4

**Comment by Cuyler36** [comment]
I'm pretty sure this was fixed already.
